### ISSUE TITLE
Feature Request: support regex extractions also for Store / Header

### ISSUE THREAD

**Issue by m-31** [Xceptance/xlt-nocoding#16]
We test the PKCE oauth flow with XLT and we have to extract parameters from the 'location' header of a response.

Currently we use the workaround: store response header value for 'location' into variable, when using the variable transform the value via beanshell call to custom extraction method.

It would be more elegant to directly extract the needed value into the variable when receiving the header response.
Perhaps something like this:

```
    - Action :
        ...
        Response :
            Store :
                - code :
                    Header : location
                    Regex : "code=([a-z0-9A-Z]*)"
                    Group : 1

      
```

**Comment by NilsHasenbanck4758** [comment]
@jowerner We tested the beta release and it worked as expected. We successfully used the new regex extraction feature for header and cookies.

**Comment by jowerner** [comment]
@NilsHasenbanck4758 Cool, thanks for your feedback! Then we are all set to prepare the final release.

**Comment by jowerner** [comment]
@NilsHasenbanck4758 xlt-nocoding 3.2.0 is available now.
