### ISSUE TITLE
Incorrect error message when mode is incorrect

### ISSUE THREAD

**Issue by rschwietzke** [Xceptance/xlt-nocoding#5]
Error message only states two modes, but three are supported

https://github.com/Xceptance/xlt-nocoding/blob/9e41b89915fcf2c4e23a201a165ed3684dfec178/src/main/java/com/xceptance/xlt/nocoding/api/AbstractNocodingTestCase.java#L105-L108

**Comment by ckeiner** [comment]
I just tried it and it shows all three modes:
![image](https://user-images.githubusercontent.com/27275355/53323784-6b442000-38df-11e9-85e3-b238a64030cd.png)
The marked code snippet also names all three modes in the error message (scroll to the side).
